# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20160512_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='Codes',
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='Colors',
        ),
    ]
