# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_auto_20160512_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehilces',
            new_name='Vehicles',
        ),
    ]
