# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_auto_20160512_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='roof_color',
            field=models.CharField(default=datetime.datetime(2016, 5, 12, 7, 4, 35, 373378, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
