# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0006_color_roof_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='engine',
            field=models.CharField(default=datetime.datetime(2016, 5, 12, 7, 16, 47, 541226, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='stop_and_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='code',
            name='transmission',
            field=models.CharField(default=datetime.datetime(2016, 5, 12, 7, 17, 12, 89350, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
