# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0007_auto_20160512_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='trim',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
