# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_auto_20160512_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='arrival_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='departure_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kaida_reg_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='option',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sagai_reg_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
