# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0009_auto_20160512_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kaida_reg_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='option',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sagai_reg_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
